### ISSUE TITLE
作者你好 ，现在使用tiktok的时候，显示 Caused by SSLError

### ISSUE THREAD

**Issue by hehekeke** [lonerge/tiktok_youtube_douyin_handling#3]
具体信息如下：
请求 https://api-h2.tiktokv.com/aweme/v1/feed/?aweme_id=7199572030474226949&version_name=26.1.3&version_code=2613&build_number=26.1.3&manifest_version_code=2613&update_version_code=2613&d2a0c4b1865379fe=6273a5108e49dfcb&uuid=0064146598573312&_rticket=1667123410000&ts=1678027531&device_brand=Google&device_type=Pixel%204&device_platform=android&resolution=1080*1920&dpi=420&os_version=10&os_api=29&carrier_region=US&sys_region=US%C2%AEion=US&app_name=trill&app_language=en&language=en&timezone_name=America/New_York&timezone_offset=-14400&channel=googleplay&ac=wifi&mcc_mnc=310260&is_my_cn=0&aid=1180&ssmix=a&as=a1qwert123&cp=cbfhckdckkde1 发生错误, 开始重试, 重试次数:1 

error: HTTPSConnectionPool(host='api-h2.tiktokv.com', port=443): Max retries exceeded with url: /aweme/v1/feed/?aweme_id=7199572030474226949&version_name=26.1.3&version_code=2613&build_number=26.1.3&manifest_version_code=2613&update_version_code=2613&d2a0c4b1865379fe=6273a5108e49dfcb&uuid=0064146598573312&_rticket=1667123410000&ts=1678027531&device_brand=Google&device_type=Pixel%204&device_platform=android&resolution=1080*1920&dpi=420&os_version=10&os_api=29&carrier_region=US&sys_region=US%C2%AEion=US&app_name=trill&app_language=en&language=en&timezone_name=America/New_York&timezone_offset=-14400&channel=googleplay&ac=wifi&mcc_mnc=310260&is_my_cn=0&aid=1180&ssmix=a&as=a1qwert123&cp=cbfhckdckkde1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by hehekeke** [comment]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/8870314/222967596-543e49f7-6f4e-4176-b35d-4782d61ea5e0.png">
更新urllib3 1.25.11 依旧出现这个错误信息

**Comment by hehekeke** [comment]
详细错误信息如下：
{'keywords': 'funny', 'video_id': '7193494861621021998', 'video_pic': 'https://p19-sign.tiktokcdn-us.com/obj/tos-useast5-p-0068-tx/2408ae37cf3a4c07b454442310b4c3ac_1674866054?x-expires=1678046400&x-signature=39zRWZM0qAiorEz47HKDFbdnVdE%3D', 'video_title': '#quebralaquebrala ', 'video_playtime': None, 'video_watch_num': 19600000, 'video_h5_url': 'https://v16-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/ecaf0cf1d0564cb4ba7d9927b46ded00/?a=1988&ch=0&cr=0&dr=0&lr=tiktok_m&cd=0%7C0%7C1%7C0&cv=1&br=2732&bt=1366&cs=0&ds=3&ft=eUQrbH6BMyqUMRr5JD1Wn48SnXtUx&mime_type=video_mp4&qs=0&rc=ZTM7ZDQ7Ozc1Zzc2aGc4M0BpamY6czM6Zjg5aTMzZzczNEBeYzE2MTFhNjYxYTBgXl5hYSNkaS1hcjRvaV5gLS1kMS9zcw%3D%3D&btag=80000&expire=1678049144&l=20230305144528AFAF64F897B235D180C8&ply_type=2&policy=2&signature=7253fbeaab5103085c78b2bc42e52ce3&tk=tt_chain_token', 'video_datafrom': 'tiktok', 'video_update_time': 1678027531.132618, 'audio_url': None}
tiktok需要更新视频数量: 36
请求 https://api-h2.tiktokv.com/aweme/v1/feed/?aweme_id=7199572030474226949&version_name=26.1.3&version_code=2613&build_number=26.1.3&manifest_version_code=2613&update_version_code=2613&d2a0c4b1865379fe=6273a5108e49dfcb&uuid=0064146598573312&_rticket=1667123410000&ts=1678027531&device_brand=Google&device_type=Pixel%204&device_platform=android&resolution=1080*1920&dpi=420&os_version=10&os_api=29&carrier_region=US&sys_region=US%C2%AEion=US&app_name=trill&app_language=en&language=en&timezone_name=America/New_York&timezone_offset=-14400&channel=googleplay&ac=wifi&mcc_mnc=310260&is_my_cn=0&aid=1180&ssmix=a&as=a1qwert123&cp=cbfhckdckkde1 发生错误, 开始重试, 重试次数:1 error: HTTPSConnectionPool(host='api-h2.tiktokv.com', port=443): Max retries exceeded with url: /aweme/v1/feed/?aweme_id=7199572030474226949&version_name=26.1.3&version_code=2613&build_number=26.1.3&manifest_version_code=2613&update_version_code=2613&d2a0c4b1865379fe=6273a5108e49dfcb&uuid=0064146598573312&_rticket=1667123410000&ts=1678027531&device_brand=Google&device_type=Pixel%204&device_platform=android&resolution=1080*1920&dpi=420&os_version=10&os_api=29&carrier_region=US&sys_region=US%C2%AEion=US&app_name=trill&app_language=en&language=en&timezone_name=America/New_York&timezone_offset=-14400&channel=googleplay&ac=wifi&mcc_mnc=310260&is_my_cn=0&aid=1180&ssmix=a&as=a1qwert123&cp=cbfhckdckkde1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
请求 https://api-h2.tiktokv.com/aweme/v1/feed/?aweme_id=7177363135760895278&version_name=26.1.3&version_code=2613&build_number=26.1.3&manifest_version_code=2613&update_version_code=2613&6d3f749ec520ba81=6273a5108e49dfcb&uuid=0594312017536468&_rticket=1667123410000&ts=1678027531&device_brand=Google&device_type=Pixel%204&device_platform=android&resolution=1080*1920&dpi=420&os_version=10&os_api=29&carrier_region=US&sys_region=US%C2%AEion=US&app_name=trill&app_language=en&language=en&timezone_name=America/New_York&timezone_offset=-14400&channel=googleplay&ac=wifi&mcc_mnc=310260&is_my_cn=0&aid=1180&ssmix=a&as=a1qwert123&cp=cbfhckdckkde1 发生错误, 开始重试, 重试次数:1 error: HTTPSConnectionPool(host='api-h2.tiktokv.com', port=443): Max retries exceeded with url: /aweme/v1/feed/?aweme_id=7177363135760895278&version_name=26.1.3&version_code=2613&build_number=26.1.3&manifest_version_code=2613&update_version_code=2613&6d3f749ec520ba81=6273a5108e49dfcb&uuid=0594312017536468&_rticket=1667123410000&ts=1678027531&device_brand=Google&device_type=Pixel%204&device_platform=android&resolution=1080*1920&dpi=420&os_version=10&os_api=29&carrier_region=US&sys_region=US%C2%AEion=US&app_name=trill&app_language=en&language=en&timezone_name=America/New_York&timezone_offset=-14400&channel=googleplay&ac=wifi&mcc_mnc=310260&is_my_cn=0&aid=1180&ssmix=a&as=a1qwert123&cp=cbfhckdckkde1 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
Traceback (most recent call last):
  File "/Users/eric/PycharmProjects/tiktok_youtube_douyin_handling/crawlers.py", line 645, in <module>
    crawler.tiktok_crawler('funny')
  File "/Users/eric/PycharmProjects/tiktok_youtube_douyin_handling/crawlers.py", line 146, in tiktok_crawler
    pool.wait()
  File "/usr/local/lib/python3.9/site-packages/threadpool.py", line 328, in wait
    self.poll(True)
  File "/usr/local/lib/python3.9/site-packages/threadpool.py", line 312, in poll
    request, result = self._results_queue.get(block=block)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/queue.py", line 171, in get
    self.not_empty.wait()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt

**Comment by hehekeke** [comment]
测试下，更换境外IP  这个问题可以正常解决
