### ISSUE TITLE
作者您好，运行时报错

### ISSUE THREAD

**Issue by Zhenghao-11** [lonerge/tiktok_youtube_douyin_handling#9]
Traceback (most recent call last):
  File "D:\pythonproject\tiktok_youtube_douyin_handling-master\timing_crawl.py", line 41, in <module>
    crawler = Crawlers()
  File "D:\pythonproject\tiktok_youtube_douyin_handling-master\crawlers.py", line 31, in __init__
    if sys.argv[1] == 'test':
IndexError: list index out of range
我是刚接触python，这个问题可能有点蠢，希望您可以抽空看一下

**Comment by lonerge** [comment]
你好, 最后两行 百度一下就知道了
if sys.argv[1] == 'test':
IndexError: list index out of range
